# Generated by Django 5.2 on 2025-05-04 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 10, 53, 36, 68475, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
